"""Add raw_file_content to BatchUpload model

Revision ID: 5ad371af564c
Revises: 4f22abdf06fc
Create Date: 2025-05-16 14:42:34.616967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad371af564c'
down_revision: Union[str, None] = '4f22abdf06fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplify to only add raw_file_content using batch_alter_table for SQLite.
    with op.batch_alter_table('batch_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_file_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Simplify to only drop raw_file_content using batch_alter_table for SQLite.
    with op.batch_alter_table('batch_uploads', schema=None) as batch_op:
        batch_op.drop_column('raw_file_content')
    # ### end Alembic commands ###
